[output]
directory = "out"               # Absolute or relative output directory
file_prefix = "map_"            # Prefix for name of the generated svg files
optimize = true                 # Use quadtree to reduce file size (recommended value: true)
visible_borders = false         # Draw borders of tiles in output (helpful for visualizing quadtree optimization)


[generation]
preset = "island_and_shore"     # The preset to use
num_iterations = 7              # The number of "split and paint" iterations

inertia = 0.5                   # How strongly the current color of a tile influences the next color of that tile. Must be in [0,1].
islands_per_iteration = 5.0     # Higher number favor creation of random islands. Must be >= 0.
lakes_per_iteration = 1.0       # Higher number favor creation of random lakes. Must be >= 0.
